---
title: "EMA lookup tables"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{EMA lookup tables}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include = FALSE}
#knitr::opts_chunk$set(include = FALSE)
library(kableExtra)
library(dplyr)
library(knitr)

#devtools::load_all()
tables <- EMAdownload:::tables

```

This document contains lookup tables for EMA data codes. Data are pulled from internal data based off of EMA internal database. This report was last run `r Sys.Date()`

## Lookup tables

```{r eval=FALSE, include=FALSE}
# In order to update this script of tables you can do several things.
#' 1. connect to akfin directly with a user name and password and pull the updated LUT tables from there
#' 2. connect to the most recent access database within NOAA ABL internal drive (must be on network to do) and update tables
#' 
#' Regardless of the method you then  update the internal tables (usethis::use_data(internal = T)) below to store tables internal to the package
# 1. connect to akfin
# con <- dbConnect(odbc::odbc(), "akfin", UID=getPass(msg="USER NAME"), PWD=getPass())
# 
# download_lut <- function(table) {
#   dbFetch(dbSendQuery(con,
#                            paste0("select * from ema.",table)))%>%
#     rename_with(tolower)%>%
#     dplyr::select(-akfin_load_date) 
# 
# }
# 
# table_vec <- c("LUT_BSIERP_REGION",
# "LUT_CATCH_LIFE_HISTORY_STAGE",
# "LUT_GEAR",
# "LUT_GEAR_DESCRIPTION",
# "LUT_GEAR_PERFORMANCE",
# "LUT_LENGTH_TYPE",
# "LUT_NBS_STRATA",
# "LUT_OCEANOGRAPHIC_DOMAIN",
# "LUT_SEX",
# "LUT_TOW_TYPE",
# "LUT_VESSEL_CODE",
# "LUT_ZOOP_STAGE_CODE",
# "LUT_TRAWL_SPECIES_TSN")
# 
# tables<-list()
# 
# for (i in 1:length(table_vec)) {
#   tables[[i]] <- download_lut(table_vec[i])
# }
#
# usethis::use_data(tables, internal = TRUE, overwrite = TRUE)


```

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}

for (i in seq_along(tables)) {

    print(
    kable(
      tables[[i]],
      format = "markdown"
    )
  )
  
  
}
```
